// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5NBIyWwxXVFAiBTQY3jEYOJ0TW4zhrhw',
    appId: '1:588035456912:web:b3a373f0b47d8e1f013d15',
    messagingSenderId: '588035456912',
    projectId: 'gdsc-hacks2025',
    authDomain: 'gdsc-hacks2025.firebaseapp.com',
    databaseURL: 'https://gdsc-hacks2025-default-rtdb.firebaseio.com',
    storageBucket: 'gdsc-hacks2025.firebasestorage.app',
    measurementId: 'G-M9Y5VK6WTG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhAWiRpw6eCfFurzIM3sOwa0nITrjprpA',
    appId: '1:588035456912:android:2113194b43c40df7013d15',
    messagingSenderId: '588035456912',
    projectId: 'gdsc-hacks2025',
    databaseURL: 'https://gdsc-hacks2025-default-rtdb.firebaseio.com',
    storageBucket: 'gdsc-hacks2025.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5NBIyWwxXVFAiBTQY3jEYOJ0TW4zhrhw',
    appId: '1:588035456912:web:3a105c2a53d0059d013d15',
    messagingSenderId: '588035456912',
    projectId: 'gdsc-hacks2025',
    authDomain: 'gdsc-hacks2025.firebaseapp.com',
    databaseURL: 'https://gdsc-hacks2025-default-rtdb.firebaseio.com',
    storageBucket: 'gdsc-hacks2025.firebasestorage.app',
    measurementId: 'G-73MQSXG1NQ',
  );
}
